# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 21:28
from __future__ import unicode_literals

import concurrency.fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import functools
import gallera.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=functools.partial(gallera.utils.generate_token, *('c',), **{}), help_text='unique identifier for chick from this system', max_length=255, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=19)),
                ('color', models.CharField(blank=True, choices=[('ROJO', 'ROJO'), ('OTRO', 'OTRO'), ('', '')], default='', max_length=4)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('idempotency_token', models.CharField(help_text='token generated by the API client that uniquely identifies this transaction', max_length=128, unique=True)),
                ('tag', models.CharField(help_text='identifier for chick', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=functools.partial(gallera.utils.generate_token, *('ow',), **{}), help_text='unique identifier for owner from this system', max_length=255, unique=True)),
                ('legal_id_type', models.CharField(blank=True, choices=[('CC', 'CC'), ('CE', 'CE'), ('NIT', 'NIT'), ('TI', 'TI'), ('PA', 'PA'), ('', '')], default='', max_length=4)),
                ('legal_id_number', models.CharField(blank=True, default='', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['legal_id_number'], name='api_gallera_legal_i_a9e995_idx'),
        ),
        migrations.AddField(
            model_name='chick',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_gallera.Owner'),
        ),
    ]
