# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 04:51
from __future__ import unicode_literals

import api_gallera.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gallera', '0003_auto_20170827_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='chick',
            name='image',
            field=models.ImageField(db_column='image', default='', upload_to=api_gallera.models.get_image_path),
        ),
    ]
