# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 02:45
from __future__ import unicode_literals

import api_gallera.models
from django.db import migrations, models
import functools
import gallera.utils


class Migration(migrations.Migration):

    dependencies = [
        ('api_gallera', '0004_chick_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chick',
            old_name='castador_name',
            new_name='breeder_name',
        ),
        migrations.RenameField(
            model_name='chick',
            old_name='castador_tag',
            new_name='breeder_plate_number',
        ),
        migrations.RenameField(
            model_name='chick',
            old_name='coliseo_tag',
            new_name='coliseo_plate_number',
        ),
        migrations.RenameField(
            model_name='chick',
            old_name='tagger_name',
            new_name='coliseo_responsible',
        ),
        migrations.RenameField(
            model_name='chick',
            old_name='born_date',
            new_name='register_date',
        ),
        migrations.RemoveField(
            model_name='chick',
            name='owner',
        ),
        migrations.AddField(
            model_name='chick',
            name='cresta',
            field=models.CharField(choices=[('PALMA', 'PALMA'), ('ROSA', 'ROSA'), ('OTRA', 'OTRA')], default='PALMA', max_length=20),
        ),
        migrations.AddField(
            model_name='chick',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chick',
            name='pata',
            field=models.CharField(choices=[('PATIBLANCO', 'PATIBLANCO'), ('PATIAMARILLO', 'PATIAMARILLO'), ('OTRO', 'OTRO')], default='PATIBLANCO', max_length=20),
        ),
        migrations.AlterField(
            model_name='chick',
            name='color',
            field=models.CharField(choices=[('CHINO', 'CHINO'), ('MORADO', 'MORADO'), ('JABADO', 'JABADO'), ('PINTO', 'PINTO'), ('OTRO', 'OTRO')], default='CHINO', max_length=20),
        ),
        migrations.AlterField(
            model_name='chick',
            name='image',
            field=models.ImageField(db_column='image', default='', editable=False, upload_to=api_gallera.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='chick',
            name='token',
            field=models.CharField(default=functools.partial(gallera.utils.generate_token, *('c',), **{}), editable=False, help_text='unique identifier for chick from this system', max_length=255, unique=True),
        ),
    ]
