# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 02:47
from __future__ import unicode_literals

import api_gallera.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gallera', '0005_auto_20170905_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chick',
            name='image',
            field=models.ImageField(db_column='image', default='', upload_to=api_gallera.models.get_image_path),
        ),
    ]
