# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_gallera', '0006_auto_20170905_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chick',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='chick',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_gallera.Owner'),
        ),
    ]
