# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 01:33
from __future__ import unicode_literals

import concurrency.fields
from django.db import migrations, models
import django.db.models.deletion
import functools
import gallera.utils


class Migration(migrations.Migration):

    dependencies = [
        ('api_gallera', '0008_remove_chick_register_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=functools.partial(gallera.utils.generate_token, *('s',), **{}), help_text='unique identifier for search from this system', max_length=30, unique=True)),
                ('count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chick',
            name='search_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_gallera.Search'),
        ),
    ]
