# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gallera', '0010_auto_20170913_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='group_date',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
