# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import functools
import gallera.utils


class Migration(migrations.Migration):

    dependencies = [
        ('api_gallera', '0011_search_group_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='token',
            field=models.CharField(default=functools.partial(gallera.utils.generate_token, *('s',), **{}), help_text='unique identifier for search from this system', max_length=255, unique=True),
        ),
    ]
